config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'api/v1/groups#index'
  scope :api do
    scope :v1 do
      resources :groups do
        member do
          post :join
          post :quit
        end
        resources :posts
      end
      scope :account do
        resources :groups
        resources :posts
      end
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true
  validates :user_id, presence: true
  default_scope -> { order(posts_count: :desc) }
  has_many :posts, dependent: :destroy
  belongs_to :user
  has_many :group_users, dependent: :destroy
  has_many :members, through: :group_users, source: :user, dependent: :destroy

end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group, counter_cache: :posts_count
  belongs_to :user
  validates :content, presence: true
  validates :group_id, presence: true
  validates :user_id, presence: true
  default_scope -> { order(updated_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :group_users, foreign_key: "user_id", dependent: :destroy
  has_many :participated_groups, through: :group_users, source: :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join_in(group)
    group_users.create(group_id: group.id)
  end

  def quit_from(group)
    group_users.find_by(group_id: group.id).destroy
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  skip_before_action :verify_authenticity_token
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.create(group_params)

    if @group.save
      current_user.join_in(@group)
      redirect_to api_v1_groups_url
    else
      render :new
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to api_v1_groups_url
    flash[:danger] = "Group has been deleted!"
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to api_v1_groups_url
      flash[:success] = "Group update successful!"
    else
      render 'edit'
    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def join
    @group = Group.find(params[:id])
    if !current_user.is_member_of?(@group)
      current_user.join_in(@group)
      flash[:success] = "You have successfully joined the group!"
    else
      flash[:warning] = "You are already a member!"
    end
    redirect_to api_v1_group_url(@group)
  end

  def quit
    @group = Group.find(params[:id])
    if current_user.is_member_of?(@group)
      current_user.quit_from(@group)
      flash[:success] = "You have successfully quitted the group!"
    else
      flash[:warning] = "You are not yet a member!"
    end
    redirect_to api_v1_group_url(@group)
  end

  private
  def group_params
    params.require(:group).permit(:title, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include ActionController::RequestForgeryProtection
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u|
    u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u|
    u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.create(group_params)

    if @group.save
      current_user.join_in(@group)
      redirect_to groups_url
    else
      render :new
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_url
    flash[:danger] = "Group has been deleted!"
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_url
      flash[:success] = "Group update successful!"
    else
      render 'edit'
    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def join
    @group = Group.find(params[:id])
    if !current_user.is_member_of?(@group)
      current_user.join_in(@group)
      flash[:success] = "You have successfully joined the group!"
    else
      flash[:warning] = "You are already a member!"
    end
    redirect_to group_url(@group)
  end

  def quit
    @group = Group.find(params[:id])
    if current_user.is_member_of?(@group)
      current_user.quit_from(@group)
      flash[:success] = "You have successfully quitted the group!"
    else
      flash[:warning] = "You are not yet a member!"
    end
    redirect_to group_url(@group)
  end

  private
  def group_params
    params.require(:group).permit(:title, :description)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_group
  before_action :find_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :membership_check, only:[:new, :create]
  def new
    @post = @group.posts.new
  end
  def create
    @post = @group.posts.build(post_params)
    @post.user = current_user
    if @post.save
      redirect_to group_path(@group)
      flash[:success] = "Post create successful!"
    else
      render 'new'
    end
  end
  def edit
    # @post = current_user.posts.find(params[:id])
  end
  def update
    if @post.update(post_params)
      redirect_to group_path(@group)
      flash[:success] = "Post update successful!"
    else
      render 'edit'
    end
  end
  def destroy
    @post.destroy
    redirect_to group_path(@group)
    flash[:danger] = "Post deleted!"
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def find_post
    @post = current_user.posts.find_by(id=params[:id])
    if !@post
      redirect_to group_path(@group)
      flash[:danger] = "You cannot modify posts which belong to others!"
    end
  end
  def membership_check
    if !current_user.is_member_of?(@group)
      redirect_to group_path(@group)
      flash[:warning] = "You cannot post in this group if you are not a member!"
    end
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">
    Design by Xiaowei Wang
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Group Talk</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("Register", new_user_registration_path) %></li>
          <li><%= link_to("Log in", new_user_session_path) %></li>
        <% else %>
          <li class= "dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi, <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("My Groups", account_groups_path) %></li>
              <li><%= link_to("My Posts", account_posts_path) %></li>
              <li><%= link_to("Account update", edit_user_registration_path) %></li>
              <li><%= link_to("Log out", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Edit group</h1>
  <hr>
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control" } %>
      <%= f.input :description, input_html: { class: "form-control" } %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
            <% if current_user?(group.user) %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-info")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-danger",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>New group</h1>
  <hr>
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control" } %>
      <%= f.input :description, input_html: { class: "form-control" } %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <% if current_user?(@group.user) %>
      <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right") %>
    <% end %>
    <%= link_to("New post", new_group_post_path(@group), class: "btn btn-success pull-right") %>
    <% if current_user %>
      <% if current_user.is_member_of?(@group) %>
        <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-danger") %>
      <% else %>
        <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-info") %>
      <% end %>
    <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>
  <table class="table">
    <thead>
      <tr>
        <th>Posts</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <td>
            <% if current_user?(post.user) %>
              <%= link_to("Edit", edit_group_post_path(post.group, post), class:"btn btn-info btn-xs") %>
              <%= link_to("Delete", group_post_path(post.group, post), class:"btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure?" }) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupTalk</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1 class="text-center">Edit post</h1>
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group, @post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control" } %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">New post</h1>
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group, @post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control" } %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>